version: "3.9"

services:

  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=eds.ordonez@yavirac.edu.ec"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/traefik.yml"
      - "./traefik/acme.json:/acme.json"
    restart: always

  flask-app:
    build: .
    container_name: flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`flask.byronrm.com`)"
      - "traefik.http.routers.flask.entrypoints=websecure"
      - "traefik.http.routers.flask.tls.certresolver=letsencrypt"
    restart: always
